name: Release

on:
  release:
    types:
      - published

jobs:

  publish:

    name: Publish

    if: github.repository_owner == 'coajs'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          yarn
          yarn build

      - name: Test
        run: |
          yarn test

      - name: Publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.AEX_NPM_TOKEN }}
        run: |
          yarn publish out --no-git-tag-version --new-version ${{ github.event.release.tag_name }}

      - name: Sync
        run: |
          sleep 5s
          yarn sync
